name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: '1'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy container
        shell: powershell
        run: docker compose up -d --build
